### ISSUE TITLE
Eroare inregistrare cerere acces

### ISSUE THREAD

**Issue by DanielaD888** [reges-ro/integrare#106]
Buna ziua,

Nu pot sa inregistrez cererea pentru accesul la registru. Am incercat de mai multe ori, nu reusesc. Aceasta e eroarea.

Reges OnlineA apărut o eroare la acordarea dreptului de acces pentru Dominte Daniela având CUI/CIF/CNP 2780923221204 la registrul firmei având CUI/CIF/CNP 36159016! System.InvalidOperationException: cannot generate an EntityKey when id is null.
   at NHibernate.Event.Default.DefaultEvictEventListener.OnEvict(EvictEvent event)
   at NHibernate.Impl.SessionImpl.FireEvict(EvictEvent evictEvent)
   at NHibernate.Impl.SessionImpl.Evict(Object obj)
   at Reges.DataAccess.RegesRepository.Save(Object e) in /src/Reges.DataAccess/RegesRepository.cs:line 41
   at RegesMessageProcessor.Processors.AngajatorProcessor.InsertAngajatorMinimal(String cui, String nume, String adresa) in /src/RegesMessageProcessor/Processors/AngajatorProcessor.cs:line 41
   at RegesMessageProcessor.Processors.CerereAccesRegistruProcessor.ProcessCerereAccesRegistru(CerereAccesRegistruReges cerereAccesRegistru, String messageKey) in /src/RegesMessageProcessor/Processors/CerereAccesRegistruProcessor.cs:line 100

**Comment by bogdannedelcu** [comment]
multumim, revenim repede

**Comment by bogdannedelcu** [comment]
a fost adresata problema, va rog verificati
